# permissions for end users to view deliveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delivery-viewer-role
rules:
- apiGroups:
  - deliverytracker.metalabs.no
  resources:
  - deliveries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deliverytracker.metalabs.no
  resources:
  - deliveries/status
  verbs:
  - get
